### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by onnimonni**
added php requirement and changed license according to https://getcomposer.org/doc/04-schema.md#license.

I just thought this is gplv3?

### CODE REVIEW

**Comment by k1sul1** [comment]
Some GPL. I've just gotten used to using GPLv2 after this: https://www.youtube.com/watch?v=PaKIZ7gJlRU

But thanks! I'd drop 5.2 support right away, but this is probably going to wp.org and currently I've no idea how I check the PHP version before activating the plugin.

**Comment by onnimonni** [comment]
You can add travis ci testing to test all commits in any php versions you want to. This way you should be more comfortable publishing it to wp.org.

**Comment by onnimonni** [comment]
Thanks for sharing the youtube video :)! You should then change it to `GPL-2.0`

**Comment by k1sul1** [comment]
Changed. WordPress is GPLv2, so it makes sense to use the same? 

Do you have any "for-dummies" getting started tutorial for travis or is it easy enough to just figure out on the way? :)

**Pull request merged**
